@Gateway.Api_HostAddress = https://localhost:7033
### Set global token variable
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwidGVuYW50SWQiOiJ0ZW5hbnQtYWJjIiwianRpIjoiMjVhNmIzODYtM2RlOS00M2NhLTk2NWEtY2VkY2QwYmFjZmJmIiwiZXhwIjoxNzUzNjM2MjU4LCJpc3MiOiJBdXRoU2VydmljZSIsImF1ZCI6IkdhdGV3YXlBUEkifQ.y2Sar1HxmIAE1QJpSzACvdxbJNqKfVoSoo_wEGNnaIQ

### Get all users
GET {{Gateway.Api_HostAddress}}/health
Accept: application/json

### Get all users
GET {{Gateway.Api_HostAddress}}/api/users
Authorization: Bearer {{token}}
Accept: application/json

### Get user by id
GET {{Gateway.Api_HostAddress}}/api/users/1
Authorization: Bearer {{token}}
Accept: application/json

### Add new user
POST {{Gateway.Api_HostAddress}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "role": "User"
}

### Get all catalogs
GET {{Gateway.Api_HostAddress}}/api/catalogs
Authorization: Bearer {{token}}
Accept: application/json

### Get catalog by id
GET {{Gateway.Api_HostAddress}}/api/catalogs/1
Authorization: Bearer {{token}}
Accept: application/json

### Add new catalog
POST {{Gateway.Api_HostAddress}}/api/catalogs
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "id": 4,
  "name": "Furniture",
  "description": "All kinds of furniture."
}